### PR TITLE
Fixed crash when record has hardware but not ends fields

### PR DESCRIPTION
**Pull request by colinjc**
When parsing our dhcpd.leases file the library was crashing on a record because it has the hardware field but not he ends field, so it tries to construct and fails with a KeyError [here](https://github.com/MartijnBraam/python-isc-dhcp-leases/blob/310e61bbba54e789453161961d66f1eaad6f382b/isc_dhcp_leases/iscdhcpleases.py#L209)
```python
        if properties['ends'] == 'never':
```

lease 172.23.251.150 {
  starts 4 2015/09/10 00:29:00;
  tstp 4 2015/09/10 00:28:44;
  tsfp 4 2015/09/10 00:29:00;
  atsfp 4 2015/09/10 00:29:00;
  binding state free;
  hardware ethernet 00:21:cc:06:94:e9;
  uid "\001\000!\314\006\224\351";
}

### CODE REVIEW

**Comment by andir** [comment]
LGTM.

Out of curiousity how did you produce that lease? Static lease?

**Comment by andir** [comment]
One more thing: Do you mind adding that kind of case to the tests?

**Comment by colinjc** [comment]
@andir Honestly, I'm not sure how the lease was produced since I had nothing to do with the configuration of the server. I assume that you're right and it is a static lease though judging from the age. 

I can quickly add a test, but I'm not sure where to add them. Should I add a record to the debian7 file and put the test in test_iscDhcpLeases.py?

**Comment by MartijnBraam** [comment]
Thanks for the contribution.

The test code should go in test_iscDhcpLeases.py and the record should go in a seperate file in the test_files directory (the same as the unittest for the options)

**Comment by MartijnBraam** [comment]
Looks great, thanks!

**Pull request merged**
